#普通数据配置
name: zhangsan
#对象的配置
person:
  name: zhangsan
  addr: nanjing
  age: 12
#配置数据、集合（普通字符串）
city:
  - beijing
  - chongqing
  - nanjing
  - xiamen
#配置数据、集合（对象数据）
student:
  - name: xiaoming
    addr: nanjing
    age: 12
  - name: lucy
    addr: beijing
    age: 15
server:
  port: 8088